
package prolab_proje_3;

import java.text.SimpleDateFormat;
import javax.swing.table.DefaultTableModel;
import java.util.*;
import java.text.*;
import javax.swing.*;

public class Kayıt_Sorgula extends javax.swing.JFrame {
Arac araba= new Arac();
int k=0;

DefaultTableModel model2;
    public Kayıt_Sorgula() {

        int i=0;
        Object [][] tablo1 = new Object[100][12];
        // Frame i oluşturan fonksiyon
        initComponents();
        JCheckBox j=new JCheckBox("asd");
       jPanel2.add(j);
        //Tablo medolleri
        DefaultTableModel model= (DefaultTableModel) jTable1.getModel();
        model2=model;
        // Markaları veritabanından çeker ve combobox a yazar
        new MySql().Sorgu_x("select distinct ArabaMarka from ilanlar ", tablo1);
        
        while (tablo1[i][0]!=null){
            jComboBox1.addItem(tablo1[i][0].toString());
            i++;
        }
        jComboBox1.setSelectedIndex(-1);
  
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        buttonGroup2 = new javax.swing.ButtonGroup();
        buttonGroup3 = new javax.swing.ButtonGroup();
        buttonGroup4 = new javax.swing.ButtonGroup();
        buttonGroup5 = new javax.swing.ButtonGroup();
        buttonGroup6 = new javax.swing.ButtonGroup();
        buttonGroup7 = new javax.swing.ButtonGroup();
        buttonGroup8 = new javax.swing.ButtonGroup();
        buttonGroup9 = new javax.swing.ButtonGroup();
        buttonGroup10 = new javax.swing.ButtonGroup();
        buttonGroup11 = new javax.swing.ButtonGroup();
        buttonGroup12 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jFormattedTextField1 = new javax.swing.JFormattedTextField();
        jFormattedTextField2 = new javax.swing.JFormattedTextField();
        jLabel9 = new javax.swing.JLabel();
        jFormattedTextField3 = new javax.swing.JFormattedTextField();
        jFormattedTextField4 = new javax.swing.JFormattedTextField();
        jLabel10 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox5 = new javax.swing.JCheckBox();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        jPanel3 = new javax.swing.JPanel();
        jCheckBox9 = new javax.swing.JCheckBox();
        jCheckBox10 = new javax.swing.JCheckBox();
        jCheckBox11 = new javax.swing.JCheckBox();
        jCheckBox12 = new javax.swing.JCheckBox();
        jCheckBox13 = new javax.swing.JCheckBox();
        jCheckBox14 = new javax.swing.JCheckBox();
        jCheckBox15 = new javax.swing.JCheckBox();
        jCheckBox16 = new javax.swing.JCheckBox();
        jCheckBox17 = new javax.swing.JCheckBox();
        jCheckBox18 = new javax.swing.JCheckBox();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jScrollPane3 = new javax.swing.JScrollPane();
        jPanel5 = new javax.swing.JPanel();
        jCheckBox19 = new javax.swing.JCheckBox();
        jCheckBox20 = new javax.swing.JCheckBox();
        jCheckBox21 = new javax.swing.JCheckBox();
        jCheckBox22 = new javax.swing.JCheckBox();
        jCheckBox23 = new javax.swing.JCheckBox();
        jCheckBox24 = new javax.swing.JCheckBox();
        jCheckBox25 = new javax.swing.JCheckBox();
        jCheckBox26 = new javax.swing.JCheckBox();
        jCheckBox27 = new javax.swing.JCheckBox();
        jCheckBox28 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jCheckBox29 = new javax.swing.JCheckBox();
        jCheckBox30 = new javax.swing.JCheckBox();
        jCheckBox31 = new javax.swing.JCheckBox();
        jCheckBox32 = new javax.swing.JCheckBox();
        jCheckBox33 = new javax.swing.JCheckBox();
        jCheckBox34 = new javax.swing.JCheckBox();
        jCheckBox35 = new javax.swing.JCheckBox();
        jCheckBox36 = new javax.swing.JCheckBox();
        jCheckBox37 = new javax.swing.JCheckBox();
        jCheckBox38 = new javax.swing.JCheckBox();
        jCheckBox39 = new javax.swing.JCheckBox();
        jButton4 = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel13 = new javax.swing.JLabel();
        jComboBox2 = new javax.swing.JComboBox<>();
        jCheckBox40 = new javax.swing.JCheckBox();
        jCheckBox41 = new javax.swing.JCheckBox();
        jCheckBox42 = new javax.swing.JCheckBox();
        jCheckBox43 = new javax.swing.JCheckBox();
        jCheckBox44 = new javax.swing.JCheckBox();
        jCheckBox45 = new javax.swing.JCheckBox();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setLocation(new java.awt.Point(50, 200));
        setUndecorated(true);
        setResizable(false);

        jPanel1.setBackground(new java.awt.Color(0, 25, 36));

        jPanel2.setBackground(new java.awt.Color(44, 62, 80));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Şehir :");

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Fiyat Aralığı :");

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("KM Aralığı :");

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("Renk :");

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Vites Türü :");

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Yakıt Türü :");

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Araç İlan Tarihi :");

        jFormattedTextField1.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField1.setToolTipText("Min");
        jFormattedTextField1.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField1FocusLost(evt);
            }
        });

        jFormattedTextField2.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField2.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField2FocusLost(evt);
            }
        });

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setForeground(new java.awt.Color(255, 255, 255));
        jLabel9.setText("-");

        jFormattedTextField3.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField3.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField3FocusLost(evt);
            }
        });

        jFormattedTextField4.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("#0"))));
        jFormattedTextField4.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextField4FocusLost(evt);
            }
        });

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("-");

        jCheckBox1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox1.setText("Manuel");

        jCheckBox2.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox2.setText("Otomatik");

        jCheckBox3.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox3.setText("Dizel");

        jCheckBox4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox4.setText("Benzin");

        jCheckBox5.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox5.setText("LPG");

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton1.setText("Son 3 Gün");

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton2.setText("Son 7 Gün");

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton3.setText("Son 15 Gün");

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Tahoma", 1, 13)); // NOI18N
        jRadioButton4.setText("Son 30 Gün");

        jScrollPane1.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane1.setInheritsPopupMenu(true);

        jCheckBox9.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox9.setText("Bej");

        jCheckBox10.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox10.setText("Beyaz");

        jCheckBox11.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox11.setText("Bordo");

        jCheckBox12.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox12.setText("Füme");

        jCheckBox13.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox13.setText("Gri");

        jCheckBox14.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox14.setText("Kahverengi");

        jCheckBox15.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox15.setText("Kırmızı");

        jCheckBox16.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox16.setText("Lacivert");

        jCheckBox17.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox17.setText("Siyah");

        jCheckBox18.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox18.setText("Mavi");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox9)
                    .addComponent(jCheckBox10)
                    .addComponent(jCheckBox11)
                    .addComponent(jCheckBox12)
                    .addComponent(jCheckBox13)
                    .addComponent(jCheckBox14)
                    .addComponent(jCheckBox15)
                    .addComponent(jCheckBox16)
                    .addComponent(jCheckBox17)
                    .addComponent(jCheckBox18))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addComponent(jCheckBox9)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox10)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox11)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox12)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox13)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox14)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox15)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox17)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox18)
                .addGap(0, 9, Short.MAX_VALUE))
        );

        jScrollPane1.setViewportView(jPanel3);

        jButton1.setBackground(new java.awt.Color(63, 195, 128));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton1.setText("Ana Menü");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(63, 195, 128));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Sorgula");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setBackground(new java.awt.Color(242, 38, 19));
        jButton3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton3.setText("Çıkış");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        jPanel4.setBackground(new java.awt.Color(248, 148, 6));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        jLabel11.setText("KAYIT SORGULA");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(614, 614, 614)
                .addComponent(jLabel11)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel11)
                .addContainerGap(42, Short.MAX_VALUE))
        );

        jTable1.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "İlanID", "İlan Adı", "Araba ID", "Marka", "Model", "KM", "Vites Türü", "Yakıt Türü", "Renk", "Şehir", "Fiyat", "Tarih"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.Double.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable1);

        jScrollPane3.setHorizontalScrollBarPolicy(javax.swing.ScrollPaneConstants.HORIZONTAL_SCROLLBAR_NEVER);
        jScrollPane3.setInheritsPopupMenu(true);

        jCheckBox19.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox19.setText("İstanbul");

        jCheckBox20.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox20.setText("Kocaeli");

        jCheckBox21.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox21.setText("Ankara");

        jCheckBox22.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox22.setText("İzmir");

        jCheckBox23.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox23.setText("Bursa");

        jCheckBox24.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox24.setText("Antalya");

        jCheckBox25.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox25.setText("Adana");

        jCheckBox26.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox26.setText("Konya");

        jCheckBox27.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox27.setText("Karabük");

        jCheckBox28.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox28.setText("Gaziantep");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jCheckBox19)
                    .addComponent(jCheckBox20)
                    .addComponent(jCheckBox21)
                    .addComponent(jCheckBox22)
                    .addComponent(jCheckBox23)
                    .addComponent(jCheckBox24)
                    .addComponent(jCheckBox25)
                    .addComponent(jCheckBox26)
                    .addComponent(jCheckBox27)
                    .addComponent(jCheckBox28))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jCheckBox19)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox20)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox21)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox22)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox23)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox24)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox25)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox26)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox27)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jCheckBox28)
                .addGap(0, 103, Short.MAX_VALUE))
        );

        jScrollPane3.setViewportView(jPanel5);

        buttonGroup12.add(jCheckBox6);
        jCheckBox6.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(0, 230, 64));
        jCheckBox6.setText("Artan");

        buttonGroup12.add(jCheckBox7);
        jCheckBox7.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(0, 230, 64));
        jCheckBox7.setText("Artan");

        buttonGroup12.add(jCheckBox8);
        jCheckBox8.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(246, 71, 71));
        jCheckBox8.setText("Azalan");

        buttonGroup12.add(jCheckBox29);
        jCheckBox29.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox29.setForeground(new java.awt.Color(0, 230, 64));
        jCheckBox29.setText("Artan");

        buttonGroup12.add(jCheckBox30);
        jCheckBox30.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox30.setForeground(new java.awt.Color(246, 71, 71));
        jCheckBox30.setText("Azalan");

        buttonGroup12.add(jCheckBox31);
        jCheckBox31.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox31.setForeground(new java.awt.Color(0, 230, 64));
        jCheckBox31.setText("Artan");

        buttonGroup12.add(jCheckBox32);
        jCheckBox32.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox32.setForeground(new java.awt.Color(246, 71, 71));
        jCheckBox32.setText("Azalan");

        buttonGroup12.add(jCheckBox33);
        jCheckBox33.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox33.setForeground(new java.awt.Color(0, 230, 64));
        jCheckBox33.setText("Artan");

        buttonGroup12.add(jCheckBox34);
        jCheckBox34.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox34.setForeground(new java.awt.Color(246, 71, 71));
        jCheckBox34.setText("Azalan");

        buttonGroup12.add(jCheckBox35);
        jCheckBox35.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox35.setForeground(new java.awt.Color(0, 230, 64));
        jCheckBox35.setText("Artan");

        buttonGroup12.add(jCheckBox36);
        jCheckBox36.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox36.setForeground(new java.awt.Color(246, 71, 71));
        jCheckBox36.setText("Azalan");
        jCheckBox36.setPreferredSize(new java.awt.Dimension(67, 25));

        buttonGroup12.add(jCheckBox37);
        jCheckBox37.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox37.setForeground(new java.awt.Color(0, 230, 64));
        jCheckBox37.setText("Artan");

        buttonGroup12.add(jCheckBox38);
        jCheckBox38.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox38.setForeground(new java.awt.Color(246, 71, 71));
        jCheckBox38.setText("Azalan");

        buttonGroup12.add(jCheckBox39);
        jCheckBox39.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox39.setForeground(new java.awt.Color(246, 71, 71));
        jCheckBox39.setText("Azalan");

        jButton4.setBackground(new java.awt.Color(204, 0, 0));
        jButton4.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jButton4.setText("Temizle");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Marka :");

        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Model :");

        buttonGroup12.add(jCheckBox40);
        jCheckBox40.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox40.setForeground(new java.awt.Color(246, 71, 71));
        jCheckBox40.setText("Azalan");

        buttonGroup12.add(jCheckBox41);
        jCheckBox41.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox41.setForeground(new java.awt.Color(0, 230, 64));
        jCheckBox41.setText("Artan");

        buttonGroup12.add(jCheckBox42);
        jCheckBox42.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox42.setForeground(new java.awt.Color(246, 71, 71));
        jCheckBox42.setText("Azalan");

        buttonGroup12.add(jCheckBox43);
        jCheckBox43.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox43.setForeground(new java.awt.Color(0, 230, 64));
        jCheckBox43.setText("Artan");

        buttonGroup12.add(jCheckBox44);
        jCheckBox44.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox44.setForeground(new java.awt.Color(246, 71, 71));
        jCheckBox44.setText("Azalan");

        buttonGroup12.add(jCheckBox45);
        jCheckBox45.setFont(new java.awt.Font("Tahoma", 1, 14)); // NOI18N
        jCheckBox45.setForeground(new java.awt.Color(0, 230, 64));
        jCheckBox45.setText("Artan");

        jTextField1.setToolTipText("");

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("İlan Adı:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(105, 105, 105)
                        .addComponent(jLabel2)
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabel4)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel7)
                                    .addComponent(jLabel8))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButton3)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton4))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox3, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox4)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox5, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jCheckBox2))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jLabel9, javax.swing.GroupLayout.PREFERRED_SIZE, 21, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jRadioButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(jRadioButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(77, 77, 77)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel12)
                                    .addComponent(jLabel5)
                                    .addComponent(jLabel13))
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 128, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE))))))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(125, 125, 125)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 1084, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(58, 58, 58)
                                .addComponent(jButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 105, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jCheckBox44, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox45, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBox43, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox42, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBox40, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox41, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox29, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox31, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox30, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox32, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox34, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox38, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox39, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox8, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, jPanel2Layout.createSequentialGroup()
                                        .addComponent(jCheckBox33, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox37, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox6, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jCheckBox7, javax.swing.GroupLayout.PREFERRED_SIZE, 89, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jCheckBox35, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jCheckBox36, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))))
                        .addGap(19, 19, 19))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 5, Short.MAX_VALUE)
                        .addComponent(jLabel1)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 216, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(149, 149, 149)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 175, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(217, 217, 217))))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel2)
                            .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jFormattedTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jFormattedTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel10)
                            .addComponent(jFormattedTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel4))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jCheckBox1)
                                .addComponent(jCheckBox2))
                            .addComponent(jLabel6, javax.swing.GroupLayout.Alignment.TRAILING))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jCheckBox3)
                            .addComponent(jCheckBox4)
                            .addComponent(jCheckBox5)
                            .addComponent(jLabel7))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton1)
                            .addComponent(jRadioButton2)
                            .addComponent(jLabel8))
                        .addGap(11, 11, 11)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jRadioButton3)
                            .addComponent(jRadioButton4))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel5)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 143, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel12)
                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jComboBox1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(jLabel1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel13)
                            .addComponent(jComboBox2, javax.swing.GroupLayout.PREFERRED_SIZE, 32, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox35)
                                    .addComponent(jCheckBox7)
                                    .addComponent(jCheckBox6)
                                    .addComponent(jCheckBox37)
                                    .addComponent(jCheckBox33)
                                    .addComponent(jCheckBox31)
                                    .addComponent(jCheckBox29)
                                    .addComponent(jCheckBox41)
                                    .addComponent(jCheckBox43)
                                    .addComponent(jCheckBox45))
                                .addGap(10, 10, 10)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(jCheckBox8)
                                    .addComponent(jCheckBox36, javax.swing.GroupLayout.PREFERRED_SIZE, 26, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jCheckBox39)
                                    .addComponent(jCheckBox38)
                                    .addComponent(jCheckBox34)
                                    .addComponent(jCheckBox32)
                                    .addComponent(jCheckBox30)
                                    .addComponent(jCheckBox40)
                                    .addComponent(jCheckBox42)
                                    .addComponent(jCheckBox44))
                                .addGap(18, 18, 18))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton4)
                                .addGap(35, 35, 35)))
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(91, 91, 91)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(91, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // Ana Menü
        setVisible(false);
        new Ana_Menu().setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // Çıkış
        System.exit(0);
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
    //SORGULA BUTONU İLK SORGU CUMLECİĞİNİ DİĞER FONKSİYONLARI ÇAĞIRARAK GÜNCELLER VE SON SORGUYU VERİTABNINA GÖNDERİR
        Object [][] tablo = new Object[100][12];
    k=0;
        String Sorgu="select * from ilanlar ";  
    Sorgu=sehir(Sorgu);
    Sorgu=vitesturu(Sorgu);
    Sorgu=yakitturu(Sorgu);
    Sorgu=tarih(Sorgu);
    Sorgu=Km(Sorgu);
    Sorgu=fiyat(Sorgu);
    Sorgu=Renk(Sorgu);
    Sorgu=Marka(Sorgu);
    Sorgu=Model(Sorgu);
    Sorgu=ilanAdi(Sorgu);
    Sorgu=Sira(Sorgu);

    //TABLOYU TEMİZLE DAHA SONRA SORGUYU GONDER VE TABLOYU GUNCELLE
    int s=model2.getRowCount();

    for(int i=s-1;i>=0;i--){
        model2.removeRow(i);
    }
        Tablo_Guncelle(Sorgu,tablo);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jFormattedTextField3FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField3FocusLost
        //FORMATTED TEXT FİELDDAN DEĞER SİLİNDİKTEN SONRA SIFIR KALMASI İÇİN
        if(jFormattedTextField3.getText().equals(""))
            jFormattedTextField3.setValue(null);
    }//GEN-LAST:event_jFormattedTextField3FocusLost

    private void jFormattedTextField4FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField4FocusLost
         //FORMATTED TEXT FİELDDAN DEĞER SİLİNDİKTEN SONRA SIFIR KALMASI İÇİN
        if(jFormattedTextField4.getText().equals(""))
            jFormattedTextField4.setValue(null);    }//GEN-LAST:event_jFormattedTextField4FocusLost

    private void jFormattedTextField1FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField1FocusLost
      //FORMATTED TEXT FİELDDAN DEĞER SİLİNDİKTEN SONRA SIFIR KALMASI İÇİN
        if(jFormattedTextField1.getText().equals(""))
            jFormattedTextField1.setValue(null);
    }//GEN-LAST:event_jFormattedTextField1FocusLost

    private void jFormattedTextField2FocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextField2FocusLost
         //FORMATTED TEXT FİELDDAN DEĞER SİLİNDİKTEN SONRA SIFIR KALMASI İÇİN
        if(jFormattedTextField2.getText().equals(""))
            jFormattedTextField2.setValue(null);    }//GEN-LAST:event_jFormattedTextField2FocusLost

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        //TEMİZLE BUTONU SIRALAMALARI VE MARKAYLA MODELLERİ SEÇİLENLERİ TEMİZLER
        buttonGroup2.clearSelection();
        buttonGroup3.clearSelection();
        buttonGroup4.clearSelection();
        buttonGroup5.clearSelection();
        buttonGroup6.clearSelection();
        buttonGroup7.clearSelection();
        buttonGroup8.clearSelection();
        buttonGroup1.clearSelection();
        buttonGroup9.clearSelection();
        buttonGroup10.clearSelection();
        buttonGroup11.clearSelection();
        buttonGroup12.clearSelection();
        jComboBox1.setSelectedIndex(-1);
        jComboBox2.setSelectedIndex(-1);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
              
// ARABA MODELLERİNİN JCOMBOBOX TA SIRLANMASI   
jComboBox2.setSelectedIndex(-1);
        
              if(jComboBox1.getSelectedIndex()!=-1){
        jComboBox2.removeAllItems();
        Object [][] tablo2 = new Object[100][12];
        int i=0;
        new MySql().Sorgu_x("select distinct ArabaModel from ilanlar where ArabaMarka like "+"'"+jComboBox1.getSelectedItem().toString()+"'", tablo2);
        
         while (tablo2[i][0]!=null){
          jComboBox2.addItem(tablo2[i][0].toString());
            i++;
        } 
              }
              jComboBox2.setSelectedIndex(-1);
    }//GEN-LAST:event_jComboBox1ActionPerformed
   
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
   
    public void Tablo_Guncelle(String Sorgu,Object[][] tablo){
     // Tablo için verileri object matrisine al ve matrisi tabloya yaz
     int i=0;
 
    new MySql().Sorgulama(Sorgu,tablo);
    while(tablo[i][0]!=null){
    model2.addRow(tablo[i]);  
    i++;
   }
}
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
    //---------------------------------------------------------// ŞEHİR FİLTRELEME //----------------------------------------------------------------------
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
    
    public String sehir(String Sorgu){
        // CHECKBOXLARI KONTROL EDER SEÇİLİ OLANLARI DİZİYE ATAR SONRASINDA SORGUYU OLUŞTURURVE KENDİNE GELEN SORGUYLA BİRLEŞTİRİR EĞER HİÇ SEÇİLİ ŞEHİR
        // YOKSA GELEN SORGU GUNCELLENMEZ SEÇİLİ OLAN VARSA K=1 YAPILIR BOYLECE DİĞER SORGULAR AND İLE BAŞLAR
     int i=0;
     String[] dizi=new String[11];
     String cumle="where Sehir in (",cumle1="";
     if(jCheckBox19.isSelected()){
         dizi[i]=jCheckBox19.getText();
         i++;
     }
      if(jCheckBox20.isSelected()){
         dizi[i]=jCheckBox20.getText();
         i++;
     }
      if(jCheckBox21.isSelected()){
         dizi[i]=jCheckBox21.getText();
         i++;
     }
     if(jCheckBox22.isSelected()){
         dizi[i]=jCheckBox22.getText();
         i++;
     }
     if(jCheckBox23.isSelected()){
         dizi[i]=jCheckBox23.getText();
         i++;
     } 
     if(jCheckBox24.isSelected()){
         dizi[i]=jCheckBox24.getText();
         i++;
     }
     if(jCheckBox25.isSelected()){
         dizi[i]=jCheckBox25.getText();
         i++;
     } 
     if(jCheckBox26.isSelected()){
         dizi[i]=jCheckBox26.getText();
         i++;
     }
     if(jCheckBox27.isSelected()){
         dizi[i]=jCheckBox27.getText();
         i++;
     } 
     if(jCheckBox28.isSelected()){
         dizi[i]=jCheckBox28.getText();
         i++;
     }
     i=0;
    
     while(dizi[i]!=null){
         cumle1=cumle1+"'"+dizi[i]+"'";
                 if(dizi[i+1]!=null)
                     cumle1=cumle1+",";
                 i++;
     }
     if(dizi[0]!=null){
         k=1;
     cumle=cumle+cumle1+")";
     Sorgu=Sorgu+cumle;
     }
     
     return Sorgu;
 }
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
    //-------------------------------------------------// VİTES TÜRÜ FİLTRELEME//--------------------------------------------------------------------------
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
    
    public String vitesturu(String Sorgu){
        int i=0;
     String[] dizi=new String[3];
     String cumle="";
     String cumle1="";
     if(k==0)
     cumle="where VitesTuru in (";
     else
     cumle=" and VitesTuru in (";
     
     if(jCheckBox1.isSelected()){
         dizi[i]=jCheckBox1.getText();
         i++;
     }
      if(jCheckBox2.isSelected()){
         dizi[i]=jCheckBox2.getText();
         i++;
     }
      //Cümlecik hazırlandı dizideki elemanlar kullanıldı
      i=0;
      while(dizi[i]!=null){
         cumle1=cumle1+"'"+dizi[i]+"'";
                 if(dizi[i+1]!=null)
                     cumle1=cumle1+",";
                 i++;
     }
      // Eğer Seçili değilse hiçbiri Sorgu cümlesi değişmez
       if(dizi[0]!=null){
         k=1;
     cumle=cumle+cumle1+")";
     Sorgu=Sorgu+cumle;
     }
     return Sorgu;
    }
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
    //---------------------------------------------------------// YAKIT TÜRÜ FİLTRELEME //-----------------------------------------------------------------
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
      public String yakitturu(String Sorgu){
        int i=0;
     String[] dizi=new String[4];
     String cumle="";
     String cumle1="";
     if(k==0)
     cumle="where YakitTuru in (";
     else
     cumle=" and YakitTuru in (";
     
     if(jCheckBox3.isSelected()){
         dizi[i]=jCheckBox3.getText();
         i++;
     }
      if(jCheckBox4.isSelected()){
         dizi[i]=jCheckBox4.getText();
         i++;
     }
      if(jCheckBox5.isSelected()){
         dizi[i]=jCheckBox5.getText();
         i++;
     }
      //Cümlecik hazırlandı dizideki elemanlar kullanıldı
      i=0;
      while(dizi[i]!=null){
         cumle1=cumle1+"'"+dizi[i]+"'";
                 if(dizi[i+1]!=null)
                     cumle1=cumle1+",";
                 i++;
     }
      // Eğer Seçili değilse hiçbiri Sorgu cümlesi değişmez
       if(dizi[0]!=null){
         k=1;
     cumle=cumle+cumle1+")";
     Sorgu=Sorgu+cumle;
     }
        

     return Sorgu;
    }
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
    //------------------------------------------------------------------// TARİH FİLTRELEME // --------------------------------------------------------------
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
      public String tarih(String Sorgu){
          
          Date bugun=new Date();
          Calendar takvim = Calendar.getInstance();
          takvim.setTime(bugun);
          takvim.add(Calendar.MONTH,1);
          String Bugun_tarih=takvim.get(Calendar.YEAR)+"-"+takvim.get(Calendar.MONTH)+"-"+takvim.get(Calendar.DAY_OF_MONTH);
         String Son_3;
         String Son_7;
         String Son_15;
         String Son_30;
          int i=0;
          String cumle="";
          String cumle1="";
          // Daha önceden farklı sorgular varsa and il sorguysa where
          if(k==0)
          cumle="where Ilan_Tarih between ";
          else
          cumle=" and Ilan_Tarih between ";
          
          if(jRadioButton1.isSelected()){
              // Tarihten filtre sayyı çıkar ve tarihi stringe çevirip sorgu cümlesini oluştur
              i=1;
              k=1;
              takvim.add(Calendar.DATE,-3);
             Son_3=takvim.get(Calendar.YEAR)+"-"+takvim.get(Calendar.MONTH)+"-"+takvim.get(Calendar.DAY_OF_MONTH);
             cumle=cumle+"'"+Son_3+"'"+" and "+"'"+Bugun_tarih+"'";
             
         }
          else if(jRadioButton2.isSelected()){
              i=1;
              k=1;
             takvim.add(Calendar.DATE,-7);
             Son_7=takvim.get(Calendar.YEAR)+"-"+takvim.get(Calendar.MONTH)+"-"+takvim.get(Calendar.DAY_OF_MONTH);
             cumle=cumle+"'"+Son_7+"'"+" and "+"'"+Bugun_tarih+"'";
        }
         else if(jRadioButton3.isSelected()){
             i=1;
             k=1;
             takvim.add(Calendar.DATE,-15);
             Son_15=takvim.get(Calendar.YEAR)+"-"+takvim.get(Calendar.MONTH)+"-"+takvim.get(Calendar.DAY_OF_MONTH);
             cumle=cumle+"'"+Son_15+"'"+" and "+"'"+Bugun_tarih+"'";
        }
         else if(jRadioButton4.isSelected()){
             i=1;
             k=1;
             takvim.add(Calendar.DATE,-30);
             Son_30=takvim.get(Calendar.YEAR)+"-"+takvim.get(Calendar.MONTH)+"-"+takvim.get(Calendar.DAY_OF_MONTH);
             cumle=cumle+"'"+Son_30+"'"+" and "+"'"+Bugun_tarih+"'";
        }
          //Seçilmişse
          if(i==1)
          Sorgu=Sorgu+cumle;
          
          return Sorgu;
      }
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
    //-------------------------------------------------------------// KM FİLTRELEME //---------------------------------------------------------------------
    //-----------------------------------------------------------------------------------------------------------------------------------------------------
      public String Km(String Sorgu){
        
          int i=0; 
          int ilan_km_min=0,ilan_km_max=1999999999;
          String cumle="";
          String cumle1="";
          
          // Daha önceden farklı sorgular varsa and il sorguysa where
          if(k==0)
          cumle="where Ilan_Km between ";
          else
          cumle=" and Ilan_Km between ";
          
          if(jFormattedTextField3.getText().trim().length()!=0){
              ilan_km_min=Integer.parseInt(jFormattedTextField3.getText());
              i=1;

          }
          else if(jFormattedTextField3.getText().trim().length()==0){
              ilan_km_min=0;
             

          }
            if(jFormattedTextField4.getText().trim().length()!=0){
               ilan_km_max=Integer.parseInt(jFormattedTextField4.getText());
               i=1;

          }
           else if(jFormattedTextField4.getText().trim().length()==0){
               ilan_km_max=1999999999;
               

          }
            
            if(i==1){
                cumle=cumle+ilan_km_min+" and "+ilan_km_max;
                Sorgu=Sorgu+cumle;
                k=1;
            }
           

          return Sorgu;
      }
 //-----------------------------------------------------------------------------------------------------------------------------------------------------
 //-------------------------------------------------------------// FİYAT FİLTRELEME //------------------------------------------------------------------
 //-----------------------------------------------------------------------------------------------------------------------------------------------------   
      public String fiyat(String Sorgu){
          
          int i=0; 
          int ilan_fiyat_min=0,ilan_fiyat_max=1999999999;
          String cumle="";
          String cumle1="";
          
          // Daha önceden farklı sorgular varsa and il sorguysa where
          if(k==0)
          cumle="where Ilan_Fiyat between ";
          else
          cumle=" and Ilan_Fiyat between ";
          
          if(jFormattedTextField1.getText().trim().length()!=0){
              ilan_fiyat_min=Integer.parseInt(jFormattedTextField1.getText());
              i=1;

          }
          else if(jFormattedTextField1.getText().trim().length()==0){
              ilan_fiyat_min=0;
             

          }
            if(jFormattedTextField2.getText().trim().length()!=0){
               ilan_fiyat_max=Integer.parseInt(jFormattedTextField2.getText());
               i=1;

          }
           else if(jFormattedTextField2.getText().trim().length()==0){
               ilan_fiyat_max=1999999999;
               

          }
            
            if(i==1){
                cumle=cumle+ilan_fiyat_min+" and "+ilan_fiyat_max;
                Sorgu=Sorgu+cumle;
                k=1;
            }
            
          return Sorgu;
      }
      
//-----------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------// RENK FİLTRELEME //-------------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------------------------------------      
       public String Renk(String Sorgu){
     int i=0;
     String[] dizi=new String[11];
     String cumle="";
     String cumle1="";
     // Daha önceden farklı sorgular varsa and il sorguysa where
     if(k==0)
       cumle="where Renk in ( ";
     else
       cumle=" and Renk in ( ";
          
     if(jCheckBox9.isSelected()){
         dizi[i]=jCheckBox9.getText();
         i++;
     }
      if(jCheckBox10.isSelected()){
         dizi[i]=jCheckBox10.getText();
         i++;
     }
      if(jCheckBox11.isSelected()){
         dizi[i]=jCheckBox11.getText();
         i++;
     }
     if(jCheckBox12.isSelected()){
         dizi[i]=jCheckBox12.getText();
         i++;
     }
     if(jCheckBox13.isSelected()){
         dizi[i]=jCheckBox13.getText();
         i++;
     } 
     if(jCheckBox14.isSelected()){
         dizi[i]=jCheckBox14.getText();
         i++;
     }
     if(jCheckBox15.isSelected()){
         dizi[i]=jCheckBox15.getText();
         i++;
     } 
     if(jCheckBox16.isSelected()){
         dizi[i]=jCheckBox16.getText();
         i++;
     }
     if(jCheckBox17.isSelected()){
         dizi[i]=jCheckBox17.getText();
         i++;
     } 
     if(jCheckBox18.isSelected()){
         dizi[i]=jCheckBox18.getText();
         i++;
     }
     i=0;
    
     while(dizi[i]!=null){
         cumle1=cumle1+"'"+dizi[i]+"'";
                 if(dizi[i+1]!=null)
                     cumle1=cumle1+",";
                 i++;
     }
     if(dizi[0]!=null){
         k=1;
     cumle=cumle+cumle1+")";
     Sorgu=Sorgu+cumle;
     }
     
     return Sorgu;
 }   
//-----------------------------------------------------------------------------------------------------------------------------------------------------
//-------------------------------------------------------------// SIRALAMA FİLTRELEME //---------------------------------------------------------------
//-----------------------------------------------------------------------------------------------------------------------------------------------------    
       
      public String Sira(String Sorgu){
          int i=0;
    // String[] dizi=new String[11];
     String cumle=" order by ";
     String cumle1="";
     // Daha önceden farklı sorgular varsa and il sorguysa where
     
          
     if(jCheckBox6.isSelected()){
         cumle1="Sehir asc,";
         i=1;
       
     }
     else if(jCheckBox39.isSelected()){
         cumle1="Sehir desc,";
         i=1;
        
     }
      if(jCheckBox7.isSelected()){
        cumle1=cumle1+"Ilan_Fiyat asc,";
        i=1;
     }
     else if(jCheckBox8.isSelected()){
         cumle1=cumle1+"Ilan_Fiyat desc,";
         i=1;
     }
     if(jCheckBox29.isSelected()){
         cumle1=cumle1+"Ilan_Km asc,";
         i=1;
     } 
    else if(jCheckBox30.isSelected()){
        cumle1=cumle1+"Ilan_Km desc,";
        i=1;
     }
     if(jCheckBox31.isSelected()){
         cumle1=cumle1+"VitesTuru asc,";
         i=1;
     } 
    else if(jCheckBox32.isSelected()){
         cumle1=cumle1+"VitesTuru desc,";
         i=1;
     }
     if(jCheckBox33.isSelected()){
        cumle1=cumle1+"YakitTuru asc,";
        i=1;
     } 
     else if(jCheckBox34.isSelected()){
         cumle1=cumle1+"YakitTuru desc,";
         i=1;
     }
     if(jCheckBox35.isSelected()){
         cumle1=cumle1+"Ilan_Tarih asc,";
         i=1;
     }
     else if(jCheckBox36.isSelected()){
         cumle1=cumle1+"Ilan_Tarih desc,";
         i=1;
     }
     if(jCheckBox37.isSelected()){
         cumle1=cumle1+"Renk asc,";
         i=1;
     }
     else if(jCheckBox38.isSelected()){
         cumle1=cumle1+"Renk desc,";
         i=1;
     }
     if(jCheckBox41.isSelected()){
         cumle1=cumle1+"ArabaModel asc,";
         i=1;
     }
     else if(jCheckBox40.isSelected()){
         cumle1=cumle1+"ArabaModel desc,";
         i=1;
         
     }
      if(jCheckBox42.isSelected()){
         cumle1=cumle1+"ArabaMarka desc,";
         i=1;
     }
     else if(jCheckBox43.isSelected()){
         cumle1=cumle1+"ArabaMarka asc,";
         i=1;
         
     }
      if(jCheckBox44.isSelected()){
         cumle1=cumle1+"ArabaID desc,";
         i=1;
     }
     else if(jCheckBox45.isSelected()){
         cumle1=cumle1+"ArabaID asc,";
         i=1;
         
     }
     
     
         if(i==1){
     cumle=cumle+cumle1;
     Sorgu=Sorgu+cumle;
     Sorgu=Sorgu.substring(0,Sorgu.length()-1);
         }
     
     System.out.println(Sorgu);
          
     return Sorgu;
         
      }
      
   public String Marka(String Sorgu){
       if(jComboBox1.getSelectedIndex()!=-1){
            int i=0;
     String[] dizi=new String[11];
     String cumle="";
     String cumle1="";
     // Daha önceden farklı sorgular varsa and il sorguysa where
     if(k==0)
       cumle="where ArabaMarka like "+"'"+jComboBox1.getSelectedItem().toString()+"'";
     else
       cumle=" and ArabaMarka like "+"'"+jComboBox1.getSelectedItem().toString()+"'";

     
         k=1;
         Sorgu=Sorgu+cumle;
     }
     
       
       
       
       return Sorgu;
       
   }
      public String Model(String Sorgu){
       if(jComboBox2.getSelectedIndex()!=-1){
            int i=0;
     String cumle="";
     String cumle1="";
     // Daha önceden farklı sorgular varsa and ilk sorguysa where
     if(k==0)
       cumle="where ArabaModel like "+"'"+jComboBox2.getSelectedItem().toString()+"'";
     else
       cumle=" and ArabaModel like "+"'"+jComboBox2.getSelectedItem().toString()+"'";
     
         k=1;
         Sorgu=Sorgu+cumle;
     }
       return Sorgu;
       
   }
  
     public String ilanAdi(String Sorgu){
       if(jTextField1.getText().equals("")!=true){
            int i=0;
     String cumle="";
     String cumle1="";
     // Daha önceden farklı sorgular varsa and ilk sorguysa where
     if(k==0)
       cumle="where Ilan_Adi like "+"'%"+jTextField1.getText()+"%'";
     else
       cumle=" and Ilan_Adi like "+"'%"+jTextField1.getText()+"%'";
     
         k=1;
         Sorgu=Sorgu+cumle;
         
     }
       return Sorgu;
       
   }
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
      
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Kayıt_Sorgula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Kayıt_Sorgula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Kayıt_Sorgula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Kayıt_Sorgula.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Kayıt_Sorgula().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.ButtonGroup buttonGroup10;
    private javax.swing.ButtonGroup buttonGroup11;
    private javax.swing.ButtonGroup buttonGroup12;
    private javax.swing.ButtonGroup buttonGroup2;
    private javax.swing.ButtonGroup buttonGroup3;
    private javax.swing.ButtonGroup buttonGroup4;
    private javax.swing.ButtonGroup buttonGroup5;
    private javax.swing.ButtonGroup buttonGroup6;
    private javax.swing.ButtonGroup buttonGroup7;
    private javax.swing.ButtonGroup buttonGroup8;
    private javax.swing.ButtonGroup buttonGroup9;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox10;
    private javax.swing.JCheckBox jCheckBox11;
    private javax.swing.JCheckBox jCheckBox12;
    private javax.swing.JCheckBox jCheckBox13;
    private javax.swing.JCheckBox jCheckBox14;
    private javax.swing.JCheckBox jCheckBox15;
    private javax.swing.JCheckBox jCheckBox16;
    private javax.swing.JCheckBox jCheckBox17;
    private javax.swing.JCheckBox jCheckBox18;
    private javax.swing.JCheckBox jCheckBox19;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox20;
    private javax.swing.JCheckBox jCheckBox21;
    private javax.swing.JCheckBox jCheckBox22;
    private javax.swing.JCheckBox jCheckBox23;
    private javax.swing.JCheckBox jCheckBox24;
    private javax.swing.JCheckBox jCheckBox25;
    private javax.swing.JCheckBox jCheckBox26;
    private javax.swing.JCheckBox jCheckBox27;
    private javax.swing.JCheckBox jCheckBox28;
    private javax.swing.JCheckBox jCheckBox29;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox30;
    private javax.swing.JCheckBox jCheckBox31;
    private javax.swing.JCheckBox jCheckBox32;
    private javax.swing.JCheckBox jCheckBox33;
    private javax.swing.JCheckBox jCheckBox34;
    private javax.swing.JCheckBox jCheckBox35;
    private javax.swing.JCheckBox jCheckBox36;
    private javax.swing.JCheckBox jCheckBox37;
    private javax.swing.JCheckBox jCheckBox38;
    private javax.swing.JCheckBox jCheckBox39;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox40;
    private javax.swing.JCheckBox jCheckBox41;
    private javax.swing.JCheckBox jCheckBox42;
    private javax.swing.JCheckBox jCheckBox43;
    private javax.swing.JCheckBox jCheckBox44;
    private javax.swing.JCheckBox jCheckBox45;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JCheckBox jCheckBox9;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JComboBox<String> jComboBox2;
    private javax.swing.JFormattedTextField jFormattedTextField1;
    private javax.swing.JFormattedTextField jFormattedTextField2;
    private javax.swing.JFormattedTextField jFormattedTextField3;
    private javax.swing.JFormattedTextField jFormattedTextField4;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField1;
    // End of variables declaration//GEN-END:variables
}
